### ISSUE TITLE
Project Kanban Board

### ISSUE THREAD

**Issue by fortuneonyeka** [fortuneonyeka/awesome-resturants#20]
This is the final cpastone project kanban board.
We are a team of 4 members: @tiagorahal , @JuliCarracedo , @fortuneonyeka, @rotimiazeez.
[link](https://github.com/fortuneonyeka/awesome-resturants/projects) to kanban board
![kanban](https://user-images.githubusercontent.com/44624138/153588062-9911a336-a88d-4b4e-b03b-01f2270fd931.png)
.

**Comment by MuriloRoque** [comment]
Hi @fortuneonyeka, @JuliCarracedo, @tiagorahal, 

Good job so far!
There are some issues that you still need to work on but you are almost there!

## Suggested changes

- [ ] Please add a screenshot of your current Kanban board to this issue's description as it written in the [requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md).

- [ ] There are some cards you created without a detailed description about what needs to be done, please add these descriptions to them, just like the in the requirements.

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by MuriloRoque** [comment]
Hi @fortuneonyeka, @JuliCarracedo, @tiagorahal,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
